# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

  after_success:
    - Rscript -e 'covr::codecov()'
CODECOV_TOKEN="6f9e789e-5ef8-4d24-bcd3-a98f157df846"
