---
title: "Project 3: STAT302package Tutorial"
author: "Alisha Luo"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{STAT302package Tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(STAT302package)
library(ggplot2)
```

## Installation
To download the STAT302package package, use the code below
```{r, eval = FALSE}
# install.packages("devtools")
# devtools::install_github("alishaluo/STAT302package")
# library(STAT302package)
```

# my_t.test function
```{r}
my_t_test(my_gapminder$pop, alternative = "two.sided", mu = 60)
my_t_test(my_gapminder$pop, alternative = "less", mu = 60)
my_t_test(my_gapminder$pop, alternative = "greater", mu = 0)
```

Assuming that the null hypothesis ($\mu$ = 60) is true, 

# my_lm function
```{r}
test <- my_lm(formula = lifeExp ~ gdpPercap + continent, data = my_gapminder)
my_coef <- test[, 1]
my_matrix <- model.matrix(lifeExp ~ gdpPercap + continent, data = my_gapminder)
y_hat <- my_matrix %*% as.matrix(my_coef)

my_data <- data.frame("Actual" = my_gapminder$lifeExp, "Fitted" = y_hat, 
                      "Continent" = my_gapminder$continent)
ggplot(my_data, aes(x = Actual, y = Fitted, color = Continent)) + 
  geom_point() + 
  theme_bw(base_size = 20)
```
